#!/usr/bin/env python3

#This is for the Extended Task 3, the location where the extended encoding code starts
#   is clearly stated and each build CNF function is labeled in order that it appears in 
#   the extended task description section of "Project 1.pdf".

import sys

from lib.reader import clean
from lib.cnf import (build_cell_cnf,
                    build_row_cnf,
                    build_column_cnf,
                    build_box_cnf,
                    build_constraints_cnf,
                    build_cell_max_cnf,
                    build_value_in_row_cnf,
                    build_value_in_column_cnf,
                    build_value_in_box_cnf)
from lib.writer import build_cnf_string

def main():
  input_str = sys.stdin.read()
  sudoku = clean(input_str)
  dimension = int(len(sudoku) ** 0.5)

  cell_cnf = build_cell_cnf(dimension)
  row_cnf = build_row_cnf(dimension)
  column_cnf = build_column_cnf(dimension)
  box_cnf = build_box_cnf(dimension)
  constraints_cnf = build_constraints_cnf(sudoku, dimension)

  # --------- Extended Encoding Code Call Start ---------
  cell_max_cnf = build_cell_max_cnf(dimension)
  value_in_row = build_value_in_row_cnf(dimension)
  value_in_column = build_value_in_column_cnf(dimension)
  value_in_box = build_value_in_box_cnf(dimension)
  # --------- Extended Encoding Code Call End ---------

  cnf_string = build_cnf_string(
    [cell_cnf, row_cnf, column_cnf, box_cnf, constraints_cnf, cell_max_cnf, value_in_row, value_in_column, value_in_box],
    dimension
  )

  print(cnf_string)

if __name__ == '__main__':
  main()
