#!/usr/bin/env python3
import sys

from lib.reader import clean
from lib.cnf import (build_cell_cnf,
                    build_row_cnf,
                    build_column_cnf,
                    build_box_cnf,
                    build_constraints_cnf)
from lib.writer import build_cnf_string

def main():
  input_str = sys.stdin.read()
  sudoku = clean(input_str)
  dimension = int(len(sudoku) ** 0.5)

  cell_cnf = build_cell_cnf(dimension)
  row_cnf = build_row_cnf(dimension)
  column_cnf = build_column_cnf(dimension)
  box_cnf = build_box_cnf(dimension)
  constraints_cnf = build_constraints_cnf(sudoku, dimension)

  cnf_string = build_cnf_string(
    [cell_cnf, row_cnf, column_cnf, box_cnf, constraints_cnf],
    dimension
  )

  print(cnf_string)

if __name__ == '__main__':
  main()
